server:
  port: 8082

spring:
  application:
    name: supermarket-delivery-cart
  data:
    mongodb:
      uri: "mongodb://localhost:27017/supermarket-cart"

api:
  supermarket:
    url: "http://localhost:8081/supermarket-delivery-products"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
